x-common-config:
  &common-config
  network_mode: host
  ipc: host

services:
  gazebo:
    image: husarion/panther-gazebo:humble-ros2-devel
    container_name: gazebo
    <<: *common-config
    runtime: nvidia
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONE_DDS_URI=file:///config/cyclonedds.xml
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config:/config
    command: >
      ros2 launch husarion_ugv_gazebo simulation.launch.py
        components_config_path:=/config/components.yaml
        namespace:=panther
        use_rviz:=False

  docking:
    image: husarion/husarion-ugv-autonomy:humble-0.1.0-20250124
    container_name: docking
    <<: *common-config
    volumes:
      - ./config:/config
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONE_DDS_URI=file:///config/cyclonedds.xml
    command: >
      ros2 launch husarion_ugv_docking docking.launch.py
        namespace:=panther
        use_wibotic_info:=False
        camera_image_topic:=${CAMERA_IMAGE_TOPIC:-/panther/camera/color/image_raw}
        camera_info_topic:=${CAMERA_INFO_TOPIC:-/panther/camera/color/camera_info}
        docking_server_config_path:=/config/docking_server.yaml
        apriltag_config_path:=/config/apriltag.yaml
        apriltag_size:=0.08
        use_sim:=True

  navigation:
    image: husarion/husarion-ugv-autonomy:humble-0.1.0-20250512
    container_name: navigation
    <<: *common-config
    volumes:
      - ./config:/config
      - ../maps:/maps
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONE_DDS_URI=file:///config/cyclonedds.xml
    command: >
      ros2 launch husarion_ugv_navigation bringup_launch.py
        namespace:=panther
        observation_topic:=/panther/velodyne_points
        observation_topic_type:=pointcloud
        pc2ls_params_file:=/config/pc2ls_params.yaml
        params_file:=/config/nav2_params.yaml
        slam:=${SLAM:-True}
        use_sim_time:=True
