x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: always

services:
  docking:
    # image: husarion/husarion-ugv-autonomy:humble-0.1.0-20250210-stable
    image: docking-wip
    container_name: docking
    <<: *common-config
    volumes:
      - ./config:/config
      - ./start.sh:/start.sh
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONE_DDS_URI=file:///config/cyclonedds.xml
    command: >
      /start.sh

  wibotic_static_transform:
    image: husarion/husarion-ugv-autonomy:humble-0.1.0-20250210-stable
    <<: *common-config
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONE_DDS_URI=file:///config/cyclonedds.xml
    command: >
      ros2 run tf2_ros static_transform_publisher 0.38 0.0 -0.08 0 0 0 lynx/cover_link lynx/wibotic_receiver_link


  # navigation:
  #   image: husarion/husarion-ugv-autonomy:humble-0.1.0-20250210-stable
  #   container_name: navigation
  #   <<: *common-config
  #   volumes:
  #     - ../maps:/maps
  #   environment:
  #     - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
  #   command: >
  #     ros2 launch husarion_ugv_navigation bringup_launch.py
  #       namespace:=panther
  #       observation_topic:=${OBSERVATION_TOPIC:-err}
  #       observation_topic_type:=${OBSERVATION_TOPIC_TYPE:-err}
  #       slam:=${SLAM:-True}
  #       use_sim_time:=False
