---
/**:
  pointcloud_to_laserscan:
    ros__parameters:
      use_sim_time: false
      min_height: 0.05
      max_height: 0.5
      angle_min: -3.14
      angle_max: 3.14
      angle_increment: 0.01
      scan_time: 0.1
      range_min: 0.85
      range_max: 12.0
      target_frame: ""
      transform_tolerance: 0.01
      inf_epsilon: 1.0
      use_inf: true
